### ISSUE TITLE
failed to detect savedata.csv as empty file

### ISSUE THREAD

**Issue by halcyoneee** [CS2103-AY1819S2-W14-1/main#122]
So I just wanted to clear all srs details by deleting everything inside of `savedata.csv`, however, it threw `Exception in Application init method`. So from linux command `hexdump -C savedata.csv` it contains `ef bb bf` as header, that's why it is not considered as empty.

Recreate this by putting the `savedata.csv` file available at our discord channel, at `data/user/` and run MainApp.

An expected outcome will be to ignore that file, treating it as no such file or something suitable instead of crashing the app.

**Comment by eugenefdw** [comment]
Seems to be UTF-8 BOM things again, will fix this in a bit
